# Generated by Django 3.0.6 on 2020-06-05 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200606_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='x',
        ),
    ]
