# Generated by Django 3.0.6 on 2020-06-06 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_student_x'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gendre',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(default='18', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, help_text='name please', max_length=40, null=True, unique=True),
        ),
    ]
