# Generated by Django 3.0.6 on 2020-06-07 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200607_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, error_messages={'unique': 'اسم محجوز'}, help_text='name please', max_length=40, null=True, unique=True),
        ),
    ]
