# Generated by Django 3.0.6 on 2020-06-07 23:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20200607_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='check',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='x5',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, help_text='name please', max_length=40, null=True, unique=True),
        ),
    ]
