# Generated by Django 3.0.6 on 2020-06-08 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20200608_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='x2',
            field=models.FileField(null=True, upload_to='myapp/upload'),
        ),
    ]
