# Generated by Django 3.0.6 on 2020-06-08 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_student_x2'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='x3',
            field=models.ImageField(null=True, upload_to='myapp/upload'),
        ),
    ]
