# Generated by Django 3.0.6 on 2020-06-08 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_student_x3'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='x4',
            field=models.TextField(null=True),
        ),
    ]
