# Generated by Django 3.0.6 on 2020-06-08 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_student_x4'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='Emaile',
        ),
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
        migrations.RemoveField(
            model_name='student',
            name='gendre',
        ),
        migrations.RemoveField(
            model_name='student',
            name='x2',
        ),
        migrations.RemoveField(
            model_name='student',
            name='x3',
        ),
        migrations.RemoveField(
            model_name='student',
            name='x4',
        ),
    ]
